[package]
name = "count-unreachable-pairs-of-nodes-in-an-undirected-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
